
name: cn-appstorereviews-from-url
on:
  workflow_dispatch:
    inputs:
      apple_app_package_url:
        description: 'apple playstore url like https://apps.apple.com/us/app/capcut-video-editor/id1500855883'
        type: enviroment
        required: True    
# schedule:
    # - cron: "00 12 * * *"
jobs:
  scrape_and_email:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install all necessary packages
        run: pip install  requests openpyxl pandas xlsxwriter
      - name: Run the scraping script
        run: python  cn-apple-url.py 
        env:
          apple_app_package_url: ${{ github.event.inputs.apple_app_package_url }}          
          appName: ${{ github.event.inputs.apple_app_package_url }}          
          appid: ${{ github.event.inputs.apple_app_package_url }}          
          
      - name: Commit and push and email if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "add new"
          git pull
          git push
