
name: cn-apple-from-id/name
on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'app name'
        type: enviroment
        required: True
      appid:
        description: 'app id '
        type: enviroment
        required: True    
# schedule:
    # - cron: "00 12 * * *"
jobs:
  scrape_and_email:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install all necessary packages
        run: pip install  requests openpyxl pandas xlsxwriter
      - name: Run the scraping script
        run: python cn-app-id-name.py
        env:
          appName: ${{ github.event.inputs.appName }}          
          appid: ${{ github.event.inputs.appid }}          
          
      - name: Commit and push and email if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add -A
          git commit -m "add new"
          git pull
          git push
