
name: search appid from app name
on:
  workflow_dispatch:
    inputs:
      appName:
        description: 'appName like "kingdom","bible"'
        type: enviroment
        required: True    
# schedule:
    # - cron: "00 12 * * *"
jobs:
  scrape_and_email:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install all necessary packages
        run: pip install  requests  
      - name: Run the scraping script
        run: python get-apple-id.py
        env:
          appName: ${{ github.event.inputs.appName }}          
#       - name: Commit and push and email if content changed
#         run: |-
#           git config user.name "Automated"
#           git config user.email "actions@users.noreply.github.com"
#           git add -A
#           git commit -m "add new"
#           git pull
#           git push
